export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary": "#006069",
        "surface-variant": "#e1e3e4",
        "surface-dim": "#d8dadb",
        "inverse-on-surface": "#eff1f2",
        "outline": "#6e797b",
        "secondary-fixed": "#cfe6f2",
        "on-primary-fixed-variant": "#004f53",
        "on-secondary-container": "#526772",
        "on-tertiary-fixed": "#001f23",
        "on-primary": "#ffffff",
        "surface-tint": "#14696d",
        "on-error-container": "#93000a",
        "tertiary-container": "#007b86",
        "surface-container-highest": "#e1e3e4",
        "on-secondary": "#ffffff",
        "on-surface-variant": "#3e494b",
        "surface-bright": "#f8fafb",
        "tertiary-fixed-dim": "#75d5e2",
        "surface-container-lowest": "#ffffff",
        "primary": "#036165",
        "on-primary-container": "#d0fdff",
        "on-secondary-fixed": "#071e27",
        "on-error": "#ffffff",
        "on-primary-fixed": "#002021",
        "on-tertiary-fixed-variant": "#004f56",
        "surface-container-high": "#e6e8e9",
        "secondary-container": "#cfe6f2",
        "on-tertiary-container": "#d8faff",
        "tertiary-fixed": "#92f1fe",
        "primary-container": "#2d7a7e",
        "inverse-surface": "#2e3132",
        "on-tertiary": "#ffffff",
        "on-surface": "#191c1d",
        "outline-variant": "#bdc8cb",
        "primary-fixed": "#a6eff3",
        "error": "#ba1a1a",
        "on-secondary-fixed-variant": "#354a53",
        "error-container": "#ffdad6",
        "inverse-primary": "#8ad3d7",
        "surface": "#f8fafb",
        "primary-fixed-dim": "#8ad3d7",
        "secondary": "#4c616c",
        "secondary-fixed-dim": "#b4cad6",
        "on-background": "#191c1d",
        "surface-container": "#eceeef",
        "background": "#f8fafb",
        "surface-container-low": "#f2f4f5"
      },
      fontFamily: {
        "headline": ["Manrope"],
        "body": ["Inter"],
        "label": ["Inter"]
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
    },
  },
  plugins: [],
}
